   --Oracle SQL Script File to Create User Accounts	
--- This file is an exact copy of the file sent to Breen Cunningham/David Hyland on Oct 4th 2018 at 8.37pm
--- The only new command added is "alter profile DEFAULT" to prevent passwords expiring:

alter profile DEFAULT limit password_life_time UNLIMITED;
			
grant connect, resource, dba to  barry  identified by barry;
grant connect, resource, dba to  noel  identified by noel;
grant connect, resource, dba to  breen  identified by breen;
grant connect, resource, dba to  david identified by  david;
grant connect, resource to HBS identified by HBS;
grant connect, resource to LMC identified by LMC;
grant connect, resource to DVD identified by DVD;
grant connect, resource to AEP identified by AEP;
grant connect, resource to AWC identified by AWC;
grant connect, resource to AAA identified by AAA;
grant connect, resource to MLA identified by MLA;
grant connect, resource to FGP identified by FGP;
grant connect, resource to KDP identified by KDP;
grant connect, resource to TCP identified by TCP;
grant connect, resource to CSI identified by CSI;
grant connect, resource to DDA identified by DDA;
grant connect, resource to OOA identified by OOA;
grant connect, resource to SSO identified by SSO;
grant connect, resource to TTA identified by TTA;
grant connect, resource to CCA identified by CCA;
grant connect, resource to HHA identified by HHA;
grant connect, resource to PPA identified by PPA;
grant connect, resource to acupuncturist identified by acupuncturist;
grant connect, resource to chiropractor identified by chiropractor;
grant connect, resource to dentist identified by dentist;
grant connect, resource to dermatologist identified by dermatologist;
grant connect, resource to doctor identified by doctor;
grant connect, resource to herbalist identified by herbalist;
grant connect, resource to optician identified by optician;
grant connect, resource to physiotherapist identified by physiotherapist;
grant connect, resource to surgeon identified by surgeon;
grant connect, resource to therapist identified by therapist;
grant connect, resource to demobld identified by demobld;
grant connect, resource to groff identified by groff;
grant connect, resource to prem identified by prem;
grant connect, resource to dreamhome identified by dreamhome;
grant connect, resource to student identified by student;
grant connect, resource to student1 identified by s1;
grant connect, resource to student2 identified by s2;
grant connect, resource to student3 identified by s3;
grant connect, resource to student4 identified by s4;
grant connect, resource to student5 identified by s5;
grant connect, resource to student6 identified by s6;
grant connect, resource to student7 identified by s7;
grant connect, resource to student8 identified by s8;
grant connect, resource to student9 identified by s9;
grant connect, resource to student10 identified by s10;
grant connect, resource to student11 identified by s11;
grant connect, resource to student12 identified by s12;
grant connect, resource to student13 identified by s13;
grant connect, resource to student14 identified by s14;
grant connect, resource to student15 identified by s15;
grant connect, resource to student16 identified by s16;
grant connect, resource to student17 identified by s17;
grant connect, resource to student18 identified by s18;
grant connect, resource to student19 identified by s19;
grant connect, resource to student20 identified by s20;
grant connect, resource to student21 identified by s21;
grant connect, resource to student22 identified by s22;
grant connect, resource to student23 identified by s23;
grant connect, resource to student24 identified by s24;
grant connect, resource to student25 identified by s25;
grant connect, resource to student26 identified by s26;
grant connect, resource to student27 identified by s27;
grant connect, resource to student28 identified by s28;
grant connect, resource to student29 identified by s29;
grant connect, resource to student30 identified by s30;
grant connect, resource to student31 identified by s31;
grant connect, resource to student32 identified by s32;
grant connect, resource to student33 identified by s33;
grant connect, resource to student34 identified by s34;
grant connect, resource to student35 identified by s35;
grant connect, resource to student36 identified by s36;
grant connect, resource to student37 identified by s37;
grant connect, resource to student38 identified by s38;
grant connect, resource to student39 identified by s39;
grant connect, resource to student40 identified by s40;
grant connect, resource to student41 identified by s41;
grant connect, resource to student42 identified by s42;
grant connect, resource to student43 identified by s43;
grant connect, resource to student44 identified by s44;
grant connect, resource to student45 identified by s45;
grant connect, resource to student46 identified by s46;
grant connect, resource to student47 identified by s47;
grant connect, resource to student48 identified by s48;
grant connect, resource to student49 identified by s49;
grant connect, resource to student50 identified by s50;

grant create view to  barrry ;
grant create view to  noel ;
grant create view to  breen ;
grant create view to  david ;
grant create view to HBS;
grant create view to LMC;
grant create view to DVD;
grant create view to AEP;
grant create view to AWC;
grant create view to AAA;
grant create view to MLA;
grant create view to FGP;
grant create view to KDP;
grant create view to TCP;
grant create view to CSI;
grant create view to DDA;
grant create view to OOA;
grant create view to SSO;
grant create view to TTA;
grant create view to CCA;
grant create view to HHA;
grant create view to PPA;
grant create view to acupuncturist;
grant create view to chiropractor;
grant create view to dentist;
grant create view to dermatologist;
grant create view to doctor;
grant create view to herbalist;
grant create view to optician;
grant create view to physiotherapist;
grant create view to surgeon;
grant create view to therapist;
grant create view to demobld;
grant create view to groff;
grant create view to prem;
grant create view to dreamhome;
grant create view to student;
grant create view to student1;
grant create view to student2;
grant create view to student3;
grant create view to student4;
grant create view to student5;
grant create view to student6;
grant create view to student7;
grant create view to student8;
grant create view to student9;
grant create view to student10;
grant create view to student11;
grant create view to student12;
grant create view to student13;
grant create view to student14;
grant create view to student15;
grant create view to student16;
grant create view to student17;
grant create view to student18;
grant create view to student19;
grant create view to student20;
grant create view to student21;
grant create view to student22;
grant create view to student23;
grant create view to student24;
grant create view to student25;
grant create view to student26;
grant create view to student27;
grant create view to student28;
grant create view to student29;
grant create view to student30;
grant create view to student31;
grant create view to student32;
grant create view to student33;
grant create view to student34;
grant create view to student35;
grant create view to student36;
grant create view to student37;
grant create view to student38;
grant create view to student39;
grant create view to student40;
grant create view to student41;
grant create view to student42;
grant create view to student43;
grant create view to student44;
grant create view to student45;
grant create view to student46;
grant create view to student47;
grant create view to student48;
grant create view to student49;
grant create view to student50;





